### ISSUE TITLE
single dash for some multi character flags?

### ISSUE THREAD

**Issue by silastittes** [vsbuffalo/msr#2]
This package is great, thanks!

At least for the version of the ms executable I have,  flags like "eM" take a single dash, but make_flag() creates a double dash which throws an error.

I didn't want to naively submit a pull request, as modifying make_flag() for ms might create errors when other executables are used (i.e. msprime). So not sure what the best fix is.

**Comment by vsbuffalo** [comment]
Oh yea — I'm still figuring out ways to deal with this. Could you send me the exact call that's causing issues? I think the right solution is to deprecate `t=10` being `-t 10` and use `.t=10` for `-t` or `..t` for `--t`.

**Comment by silastittes** [comment]
res <- call_ms(nsam = 10, howmany = 1, I = c(2, 5, 5), eM = c(0, .1), t = 20) %>% parse_ms()

returns

Error in sims[, colorder] : incorrect number of dimensions
In addition: Warning message:
running command 'ms 10 1 -I 2 5 5 --eM 0 0.1 -t 20' had status 1

**Comment by silastittes** [comment]
my simple fix was just to keep the dash variable as "-" in the make_flag() function, regardless of nchar length.

**Comment by vsbuffalo** [comment]
I'm the worst and got caught up with projects and didn't fix this. But then I needed it for my project, so I fixed it... So, now there's strict mode which converts `.` to `-`:

    call_ms(10, 10, .t=10, .seeds=c(1,2,3), strict=TRUE)

This keeps backward compatibility but allows for the safer option. I'll deprecate the original way eventually...
