### ISSUE TITLE
Can't get the package to install

### ISSUE THREAD

**Issue by Neato-Nick** [vsbuffalo/msr#3]
Hi,

I love this idea for a package, and I dig the tidy-friendly way of manipulating the data. I don't see in the readme how I can install it, though?

I tried using devtools::install_github but that didn't work.

On a related note, is it because of namespace issues with the existing but unrelated package [msr](https://cran.r-project.org/web/packages/msr/index.html)?

**Comment by vsbuffalo** [comment]
Could you provide the error message? Installing via github works for me. Please make sure you're using the latest R and devtools packages.

**Comment by Neato-Nick** [comment]
I'm using the last version of R (3.4.3), will I need to upgrade for the package to run? Also, I'm running devtools 1.13.5
```
devtools::install_github("git@github.com:vsbuffalo/msr.git")
#> Downloading GitHub repo git@github.com:vsbuffalo/msr.git@master
#> from URL https://api.github.com/repos/git@github.com:vsbuffalo/msr.git/zipball/master
#> Installation failed: Not Found (404)
```

**Comment by vsbuffalo** [comment]
Try just 

```r
devtools::install_github('vsbuffalo/msr')
```

**Comment by Neato-Nick** [comment]
Thanks - that worked! I'll try linking the repo instead of the URL directly next time.

**Comment by vsbuffalo** [comment]
Cool, glad that worked. Hope msr is useful!
